### ISSUE TITLE
Proposal: rich syntax for "each" data-query

### ISSUE THREAD

**Issue by vird** [astoilkov/jsblocks#1]
bad: data-query="each(items.view)"
http://jsblocks.com/api/blocks-queries-each
There is no possibility to make 2 cycles with different $this

Better, but ugly syntax: data-bind="foreach: { data: categories, as: 'category' }"
http://knockoutjs.com/documentation/foreach-binding.html

Best but not compatible: ng-repeat="model in collection" https://docs.angularjs.org/api/ng/directive/ngRepeat
angular-like syntax is powerful, but this is not pure js

proposal 1:
data-query="each(collection)" data-iterator="model" (for array)
data-query="each(collection)" data-iterator-key="key" data-iterator-key="value"
it's possible to make 2 nested loops with different iterators. A little bit bloat syntax for array and really bloat syntax for objects

proposal 2:
data-query="each(collection, index, value)" (for array)
data-query="each(collection, key, value)" (for object)
better syntax, but index, key and value are not defined, so workaround will be not very simple and clear. Not extendable with new stuff

proposal 3:
data-query="each(collection).index('index_name').value('value_name')" (for array)
data-query="each(collection).key('key_name').value('key_name')" (for object)
more text, but it's javascript. There is not such big problem to extend "key", "index" and "value" methods.

proposal 4:
data-query="as({index:'index'}).each(collection)"
even better, but a little bit strange order.
There is no need to change each(), you only add "as" data-query with method "each".

proposal 4.1:
data-query="index('index').each(collection)"
proposal 3 + proposal 4 combination. Fully compatible with proposal 4

**Comment by astoilkov** [comment]
Hi,

Great to have my first question. With the current implementation you could do two things:

```html
<div data-query="each(items)">
    <!-- this will work because define is called before each -->
    <div data-query="define('item', $this).each(innerItems)">
        <!-- The item is defined and could be used in inner context changes -->
        {{item.property}}
    </div>
</div>
```

OR

```html
<div data-query="each(items)">
    <div data-query="each(innerItems)">
        <!-- The $parent points to the parent context -->
        {{$parent.property}}
    </div>
</div>
```

However, I am thinking of introducing a second parameter for the `each()` query in order to allow for custom naming like this:
```html
<div data-query="each(items, 'item')">
    <div data-query="each(innerItems)">
        {{item.property}}
    </div>
</div>
```

You could read more about contexts [here](http://jsblocks.com/learn/syntax-context-properties).

**Comment by astoilkov** [comment]
I am closing this one. Lack of activity.
