### ISSUE TITLE
Blocks is executing View.ready() before DOM is populated

### ISSUE THREAD

**Issue by thaapaniemi** [astoilkov/jsblocks#105]
When web page is loaded, Blocks is executing selected views View.ready() before DOM is populated with template.

Here is simple example: https://github.com/thaapaniemi/jsblocks_i0
First console.log shows value from index.html, not content of a.html

**Comment by astoilkov** [comment]
Yes. This was fixed in a previous version. I created a pull request and changed the link to the newest jsblocks version. https://github.com/thaapaniemi/jsblocks_i0/pull/1

**Comment by thaapaniemi** [comment]
Thanks for the information. I took the blocks.js from http://jsblocks.com/ and didn't notice that there was newer version availabe.
