### ISSUE TITLE
somes questions : how to...

### ISSUE THREAD

**Issue by vbx** [astoilkov/jsblocks#108]
hello, 
how to replace POST with update & delete méthod when sync.
blocks.DataSource.prototype.options.delete.type = "PUT"
blocks.DataSource.prototype.options.delete.type = "DELETE"
good practice ?

How to trad ? i18n module ?
Or approuve you https://github.com/derkan/jsblocks.I18n ?

How to upload file, one example ?

thanks

**Comment by astoilkov** [comment]
I would suggest posting this on Gitter so there is a big chance that others
will also help. Regarding your questions:

   - you could put the type in the options of a Model or Collection
App.Model({
  options: {
    delete: {
      type: 'DELETE'
    },

    update: {
       type: 'PUT'
    }
  }
});

 - Yeah. You could definitely  use i18 module if you want. It have been
used in another project so it should work. However, I haven't used for my
own projects.

 - Uploading a file should be as easy as placing the according input in the
HTML. JSBlocks don't have specific support for this scenario. You could ask
for more info on Gitter maybe someone have done it before and could suggest
you a solution.

Hope the information helps.
Antonio

**Comment by astoilkov** [comment]
I am closing this. Feel free to open a new issue if you have more questions.
