### ISSUE TITLE
Nested views with lazy loading not working correctly

### ISSUE THREAD

**Issue by g00glen00b** [astoilkov/jsblocks#11]
I tried to reproduce the same behavior as in my previous ticket (#7) and I think I know what's going on. It seems that nested views with lazy loaded templates are not working correctly.

For example, if I take the example from the [Nested views page](http://jsblocks.com/learn/view-nested-views) and I "convert" the Navigation/Article view with a lazy loaded template, it still works fine. However, when I also replace the Blog view with a lazy loaded template, then that view is still rendered correctly, but the child views no longer load.

Here's a small Plunker code example showing the issue: http://plnkr.co/edit/OJDNpDdo8XDDFw37MFbs?p=preview

**Comment by astoilkov** [comment]
Successfully replicated the problem. Will look at a fix for the problem as soon as possible.

**Comment by astoilkov** [comment]
Hmm. Interesting. Do you run these examples on your local machine? And are you running them with npm start that opens a http server? I am getting mixed results. I have tried the code on my machine and everything seems to work correctly. Could you take a look at the project [here](https://dl.dropboxusercontent.com/u/4277603/jsblocks-seed-nested-views.zip)?

Navigate to the project using the console and execute these commands:
```
npm install

npm start
```

**Comment by g00glen00b** [comment]
Hmm, that project indeed works. Though, I modified it a bit and then sometimes one of the two inner childs would not load either.

**Comment by astoilkov** [comment]
OK. I have tested a lot and I think I have an idea why it sometimes does not work. When the parent view is too big (as a file size) and loads after the child views the child views do not get rendered. I will investigate further and let you know.
