### ISSUE TITLE
DOM not updating correctly when reseting model with collection.

### ISSUE THREAD

**Issue by Kanaye** [astoilkov/jsblocks#116]
http://jsfiddle.net/ascjsj2u/3/

**Comment by Kanaye** [comment]
Okay this one is kind of easy:
When a Model gets a ``.reset()`` call it passes ``undefined`` to the observables. 
[Here](https://github.com/astoilkov/jsblocks/blob/9bd1f1d7df539f469551308a8eee4866bb9b037c/src/query/observable.js#L40) is a check if the new value is an array if not (like in this case) the ``__value__`` property gets just overwritten with the new value (here ``undefined``). The ``èach()`` data-query gets `ùndefined`` instead of an array and does not know what to do with it, so it fails.

My question is:
Does it make sense to allow an array observable to get something else ?

An example:
We have an array observable:
```javascript
var myArrayObservable = blocks.observable(['some', 'stuff', 'in', 'an', 'array']);
```
Now we can modified it with the methods an array observable has: 
e.g. add:
```javascript
myArrayObservable.add('More strings');
```
All nice till now.
But if we pass e.g. a string to the observable:
```javascript
myArrayObservable('Oh that will be painfull');
```

Now we have an observable containing a string with array methods.
But they will fail. 
E.g. we have an ajax request or something else async ongoing and it tries to add someting again:
```javascript
myArrayObservable.add('hey i\'m async'); 
// => Uncaught TypeError: Cannot read property 'apply' of undefined(…)
```
and the other methods will most likely fail too.

I think we should better wrap the non-array value we get in an array:
e.g.  or just reset it to an empty array in case of ``undefined``.
At least I like that behaviour more.

What do you think ?

**Comment by astoilkov** [comment]
I propose the following behavior:
  - passing `undefined` or `null` to `observable()` or `reset()` method causes the observable to become empty array
  - passing any other data type wouldn't do anything and will throw a debug error message(do you know how to throw debug messages?)

What do you think about this approach?

**Comment by Kanaye** [comment]
I like that approach. 
And no, I don't know how to throw debug messages.
I will have to take a look at it.
