### ISSUE TITLE
Add a Paging example

### ISSUE THREAD

**Issue by daslicht** [astoilkov/jsblocks#117]
Hi,
a paging example is missing here:

http://jsblocks.com/learn/collection-filtering-sorting-paging

––– - -

should that be solved by using skip & take ?:

http://jsblocks.com/api/blocks-observable-extenders-skip
http://jsblocks.com/api/blocks-observable-extenders-take
?

**Comment by Kanaye** [comment]
Yeah it's using skip & take. 
You can take a look at the [shopping example](https://github.com/astoilkov/jsblocks-shopping-example/blob/bde828e53782b3e49d2491f0dee8527823ba6154/app/js/app.js#L73-L94) it's implemented there.

**Comment by daslicht** [comment]
Thank you !

**Comment by daslicht** [comment]
Do *Skip* and *Take* run client side ? 
Will they influence the ajax call or do we need to load all data before paging?

**Comment by Kanaye** [comment]
The initial rendering is server side including the skip and take. Everything after the initial load will get executed client side, so the data will get loaded via ajax.

**Comment by daslicht** [comment]
awesome ! so no need to implement custom routes with parameters
