### ISSUE TITLE
Nested Model

### ISSUE THREAD

**Issue by chardy** [astoilkov/jsblocks#121]
Hi,

I have a API return from server that returning JSON below:

```javascript

[{"id":1, "name" : "Food and Beverage", "children":[{"id":6, "name" : "Kiosk"},
                                                    {"id":7, "name" : "Outlet"}]},
 {"id":2, "name" : "Supermarket","children":[]},
 {"id":3, "name" : "Retail", "children":[{"id":4, "name" : "Clothing"},
                                         {"id":5, "name" : "Convenience Store"}]}
]

```

How do I construct Model and Collection. And how I perform .read, currently I am using $.ajax call then assign it observable array to populate it inside init (view). I am looking for better way to do this. 

```javascript

  App.View('IndustryListing', {
    industries : blocks.observable([]),
    options: {
      route: blocks.route('/admin/industries'),
      url: '/views/industries/index.html',
      preload: false
    },

    init: function () {
      var _this = this;

      $.ajax({
        url: listing_url,
        data: {
           super_admin_token: superadmin_token
        },
        error: function() {
          alert("Server error!")
        },
        dataType: 'json',
        success: function(data) {
          _this.industries = data;
        },
        type: 'GET'
      });

    }

```

Thanks for the help.

**Comment by Kanaye** [comment]
I created a short [example](https://jsfiddle.net/juj830r9/1/) with your JSON.
It's not using AJAX but shows how to do it.
Feel free to ask questions if you have some.

**Comment by chardy** [comment]
Hi @Kanaye 

Thank you. 

May I know if I am using $.ajax call, in which View callback I should trigger? I notice sometime the view is not updated. I tried to inspect and print our the sequence of the rendering view sequence, it seems like the view render faster than result returned from the ajax call. Since ajax is async, anyway for me to trigger the rendering of the view after the ajax data is returned? For example: inside the  init: function() I can call this.render(this.newCollection).

Do you have better suggestion if I need ajax call to acquire the data? I am having difficulty with .read, because of the limitation of the parameter that I can pass in to the API call. My current backend require flexible parameters based on certain query, I am now porting our front end to use jsblocks.

Thanks for the help.

**Comment by Kanaye** [comment]
You shouldn't need to tell jsblocks to render a View.
If you update the Observables it should rerender itself the parts that changed.
I [updated the example](https://jsfiddle.net/juj830r9/5/) to fill in the data async after 5 seconds.

**Comment by chardy** [comment]
Thanks :-)
