### ISSUE TITLE
Select to map to Model with options data-query

### ISSUE THREAD

**Issue by chardy** [astoilkov/jsblocks#123]
How I can do select map it to Model value?

Is this below is the right way?

```javascript

App.View('AccountEdit', {
  options: {
      route: '/admin/account/{{id}}/edit',
      url: '/views/accounts/account.html',
      preload: false
  },
  account: Account(),
  employees: 
    [
      { name: '50 employees', value: 50 },
      { name: '60 employees', value: 60 },
      { name: '70 employees', value: 70 },
      { name: '80 employees', value: 80 },
      { name: '90 employees', value: 90 },
      { name: '100 employees', value: 100 },
    ],

```

```javascript

<select data-query="options($view.employees, { text: 'name', value: 'value', caption: 'Select' }).val(number_of_employees)">

```

I tried that, but accout.number_of_employees always return undefined. What is the right way to do that?

Thanks for the help.

**Comment by chardy** [comment]
I tried .change like below:

```javascript

<select data-query="options($view.employees, { text: 'name', value: 'value', caption: 'Select' }).val(number_of_employees).on('change', $view.check_employee)">

```

It seems like the event change is not being triggered.

Do you also have example for: multiple select group, radio button group and check box group?

Appreciate much for this.

Thanks.

**Comment by Kanaye** [comment]
Hey  @chardy,
It sounds like  you have trouble with [contexts](http://jsblocks.com/learn/syntax-context-properties). The ``val()`` and the ``on('change')`` data-queries are working just fine.  [Here your example](https://jsfiddle.net/Lcay3cxw/1/).

I looked into the code and it seems that the ``val``data-query is (currently) not supporting multiselects, groups of radio buttons or groups of check boxes.

I can implement support for multiselects easily.
I'm thinking of filling the observable passed to the ``val`` query with an array of the values:
```html
<select multiple data-query="val(myValues)">
   <option value="number1">Number One</option>
   <option value="number2">Number 2</option>
</select> 
``` 
If both are selected the ``myValues``-observable would contain ``['number1', 'number2']``.
What do you think @astoilkov ?

Regarding the check box and radio button groups:
I have to look into them as I haven't used them a long time.  
The designers I work with have ideas are not possible with the limited possibilities the html elements provide.

I will post here if I have further notes.

**Comment by astoilkov** [comment]
Hmm there is some logic associated with this scenario:
  - https://github.com/astoilkov/jsblocks/blob/master/src/query/VirtualElement.js#L166
  - https://github.com/astoilkov/jsblocks/blob/master/src/query/VirtualElement.js#L603-L609

We should see why it doesn't work. Am I correct @Kanaye or I am missing something?

**Comment by Kanaye** [comment]
Okay, I missed
https://github.com/astoilkov/jsblocks/blob/master/src/query/VirtualElement.js#L166 
but that seems to be set only and [not to be working](https://jsfiddle.net/o40orgmv/).

As far as I know, this will only be executed initialy and not on update (at least in most cases) 
https://github.com/astoilkov/jsblocks/blob/master/src/query/VirtualElement.js#L603-L609.

I've been looking for something more like:
https://github.com/astoilkov/jsblocks/blob/1123d4f6ef5dfcdaba7a98765d8b1a1d5a36e30e/src/query/DomQuery.js#L362-L377

I will look into this further.

**Comment by chardy** [comment]
Thanks. Let me know if you have solution for multiselects, radio and checkbox. Right now, I just use jquery to pass checkbox value the data in observable.

**Comment by Kanaye** [comment]
Ironically the code I linked is the logic for the ``multiple```-selects.
Also radio buttons are working fine (was my mistake when I tested this):
```html
<input type="radio" data-query="checked(myValueObservable)" value="value1" />
<input type="radio" data-query="checked(myValueObservable)" value="value2" />
<!-- ... -->
```
```javascript
/* ... */
App.View(/* ...*/, {
   myValueObservable: blocks.observable('') 
  /*...*/
}):;
```
then clicking the first radiobutton the value of ``myValueObservable`` will be ``value1``.

Also multi-selects are working but currently the ``multiple`` attribute must have a value (e.g. ``multiple="multiple"``).
As writing only ``multiple`` is shorter and valid with HTML5 i will fix that.

I also will add support for checkbox-groups shouldn't be hard, so PR is kind of on it's way :smile:.
