### ISSUE TITLE
More jQuery 

### ISSUE THREAD

**Issue by TheSpiderPig** [astoilkov/jsblocks#13]
This framework needs more jQuery. 

http://needsmorejquery.com/

**Comment by desertlion** [comment]
-_-

**Comment by Stephn-R** [comment]
Is this a joke?

**Comment by astoilkov** [comment]
Ha ha. This is a nice one. Are you serious about the more jQuery. If you are please provide more information. :)

**Comment by SuggeElson** [comment]
My god :) this made my day :dancer:

**Comment by TheSpiderPig** [comment]
It's much easier to solve than needing more jpeg. 

http://needsmorejpeg.com/

**Comment by astoilkov** [comment]
Ha ha. I am closing this one. :)
