### ISSUE TITLE
How to disable print log in the console for production mode?

### ISSUE THREAD

**Issue by chardy** [astoilkov/jsblocks#134]
Hi,

Right now, the jsblocks framework always print out a lot of warning message. How I can disable that for production environment?

Please see the attached image.

Thanks.

<img width="1393" alt="screen shot 2016-03-04 at 3 20 27 pm" src="https://cloud.githubusercontent.com/assets/26913/13520604/ba43281c-e21c-11e5-89d4-6831464f5949.png">

**Comment by Kanaye** [comment]
Hey @chardy,
there are two ways to disable these messages:
You can disable them with: ``blocks.debug.disable()`` or the better way: swap your blocks.js with the blocks.min.js. The blocks.min.js-file deosn't even contain the code for printing those messages and is therefore also smaller.

**Comment by chardy** [comment]
Hi @Kanaye 

Thanks. I tried, `blocks.debug.disable()` seems like not working, but blocks.min.js indeed did not print out the console messages.
