### ISSUE TITLE
Roadmap e.g. custom components, fixes

### ISSUE THREAD

**Issue by aliakakis** [astoilkov/jsblocks#135]
Hello,

Excellent library but I wanted to ask whether you could share a future roadmap for things like custom components, fixes etc.

**Comment by Kanaye** [comment]
Hey @aliakakis,
unfortunatly Antonio is working full-time (afaik) on [caret](http://caret.io/) and I'm currently busy with other projects. I hope to get some time to work on jsblocks this month but I can't guarantee anything. Therefore it's currently not possible to share a roadmap :disappointed:.
Sorry for that.
Greetings from Germany

**Comment by aliakakis** [comment]
Hello

Thank you for the quick reply :). I am considering jsblocks for a project thus the answer on the roadmap since I saw there was some time for a release. I hope the best for both :)

**Comment by astoilkov** [comment]
Hi @aliakakis,

@Kanaye is correct. It seems we both have a lot of work currently. I am closing this now but if in the future me or @Kanaye have more time we could write here to let you know.

Have a great day.
