### ISSUE TITLE
The push state is not working when I press back button from my browser.

### ISSUE THREAD

**Issue by chardy** [astoilkov/jsblocks#137]
Hi,

Just want to check this: 
The push state is not working when I press back button from my browser. It seems like the routed function did not pick this up, but when I am on blank screen, and I refresh, it picked up and display properly. I tried many times, it has the same result when I press browser back button. 

Any mis configuration that I might miss out?

Anyway to fix this issue?

Thanks.

**Comment by Kanaye** [comment]
I'm not able to reproduce this, but the push-state history is know for beeing inconsistent between different browsers.
Can you provide a little bit more details:
 - Which browser and os are you using?
 - Which jsblocks version are you using?
 - Can you provide a little example where that occurs ?

**Comment by chardy** [comment]
Hi @Kanaye,

This happen to any browsers. I am not using jsblocks node build, I am using jsblocks 0.3.4 with Ruby on Rails. Everything works fine, just the back button is not consistent, sometime it display, sometime it just displayed blank div for view.

I think it happen only when initiate the view, somehow when we press the back button, the event is not triggered.

**Comment by Kanaye** [comment]
Hey @chardy.

Sorry, I somehow missed your response. 
Not sure how.

I tested the [jsblocks-shopping-example](https://github.com/astoilkov/jsblocks-shopping-example) in Edge, Firefox and Chrome on Windows with jsblocks version 0.3.4 and with serverside rendering disabled (static http server). 
I couldn't reproduce the issue you described above.

Can you provide a short example where this error occurs ?

**Comment by Kanaye** [comment]
Hey @chardy,
can you test if the problem exists on [that page](https://jsblocks-test.cdn.kanaye.net)  ?
It's basically a nginx-instance delivering the static files and the index.html on 404.
Okay it's just 2 views but it should be enough to test :smile:.

**Comment by Kanaye** [comment]
Hey @chardy,

we discussed this Issue per mail. So, Can you close this issue ?
Thank you.
Greeting from Germany and happy coding 😄

**Comment by chardy** [comment]
I found the solution. If you break your page into multiple js and multiple page, we can just use this hack:

`
window.onpopstate = function(event) {
  window.location.replace(document.location);
};
`
