### ISSUE TITLE
Is it possible to create custom components?

### ISSUE THREAD

**Issue by MikeBild** [astoilkov/jsblocks#14]
Like AngularJS directives or KnockoutJS components?

**Comment by astoilkov** [comment]
You could take a look at [custom queries](http://jsblocks.com/learn/queries-creating-a-custom-query). It is similar to AngularJS directives.

However, custom components / elements are still not implemented in jsblocks. I want to make them right and not rush with the implementation.

**Comment by astoilkov** [comment]
I am closing this one. If you need additional information reopen the issue or open a new one.
