### ISSUE TITLE
How to use reuse HTML Tags?

### ISSUE THREAD

**Issue by KrishnaPG** [astoilkov/jsblocks#152]
I am evaluating different frameworks and this one looks interesting - but have a question:

On multiple pages, most of the portions of the HTML is same (such as sidebars, panels, widgets etc.).

I can see that with views, it is easy to reuse the data - but I am interested in being able to reuse the 'HTML tags' - is it possible?

For example, being able to do 
````
 <authors-list>
    <author data-query="each(authors)">
         {{name}}, {{image}} etc..
     </author>
<authors-list>

<page1>
  <authors-list></authors-list>  
</page1>

<page2>
  <sidebar><authors-list></authors-list></sidebar>
</page2>
````
Here above, I am able to reuse the `<authors-list>` tag just once composed on different pages (and on different sections of same page) etc...

The goal is to compose complex widgets, out of reused tags. For example, [https://riotgear.js.org/](https://riotgear.js.org/)

It is possible to achieve such reuse with this framework? It looks like with this framework we have to keep writing the same markup all again when needed without being able to reuse the old markup. Any info could be valuable to clarify.

**Comment by Kanaye** [comment]
Hi @KrishnaPG!

It sounds like you are looking for the [template-data-query](http://jsblocks.com/api/blocks-queries-template).

Here your example from above with usage of the template data-query:
```html
<script id="authorsList" type="blocks-template">
	<div data-query="each(authors)">
    <author>
           {{name}}, {{description}} etc..
     </author>
   </div>
</script>

<div class="page1">
  <div data-query="template(authorsList)"></div>
</div>

<div class="page2">
  <sidebar>
    <div data-query="template(authorsList)"></div>
  </sidebar>
</div>
```
and [here](https://jsfiddle.net/7tkrmb93/2/) the same example as a jsfiddle.

**Comment by KrishnaPG** [comment]
Thank you @Kanaye
