### ISSUE TITLE
Add a method to execute expressions for external libs.

### ISSUE THREAD

**Issue by Kanaye** [astoilkov/jsblocks#154]
I would like to add something like ``blocks.executeExpression()`` for libraries extending jsblocks to have a way for executing expressions the way jsblocks does it.

I'm thinking about something like:
```javascript
blocks.executeExpression('2+2 is {{value + observableValue()}}', {value: 2, observableValue: blocks.observable(2)}); // => "2+2 is 4"
```

What do you think?

**Comment by astoilkov** [comment]
Nice. That looks great. Do you have a use case where this could be used?

**Comment by Kanaye** [comment]
I have some more or less clean libraries, mostly bindings for third party libraries like  [chartjs](http://www.chartjs.org/) I may want to release to public.

But currently this (and some other stuff) leaves some bad code smells I want to clean up first.

For example I'm providing configuration-options to transform a collection to data chartjs can work with, this will make that much easier.

**Comment by astoilkov** [comment]
Ok. Great. This sounds great.

**Comment by Kanaye** [comment]
I decided to also add an options argument.
So the additional use would be like that:
```javascript

blocks.executeExpression("{{test}} some words {{testObservable}}", {test: 1, testObservable("some observable")}, {raw: true});
// return something like that
[
    {observables: [], value: 1, result: "1"},
    {observables: [], value: " some words ", result: " some words "},
    {observables: [/*the testObservable here*/], value: /* testObservable here */, result: "some observable"}
]
```
this allows to subscribe to obseravbles (if necessary) and also gives the option to retain the values in an non-stringified form.

**Comment by astoilkov** [comment]
This looks like a very powerful feature.
