### ISSUE TITLE
Make models behavior for non obervable value consistent.

### ISSUE THREAD

**Issue by Kanaye** [astoilkov/jsblocks#155]
If we have an model (like in the example below) and add a non obervable (and non property) value to the model it is a simple value as long as it does not get initialized with a value.
If we pass a value to the constructor that doesn't exist in the model it also get's wrapped as an observable.

This is unexpected behavior and can lead to some strange bugs.

Expected (or at least stable behavior):

1. All non-obervable values get wrapped into an observable except the ``options`` and functions.
2. All non-observable values stay as they are except when they are specified as an obervable in the model.

I think I like the first one more.
New developers might not expect it but I think it is cleaner and more flexible than the second.

Look at the values of ``someSimpleValue`` ``someSimpleOverriddenValue`` and ``someNonModelValue``.
The other values are just some tests.

https://jsfiddle.net/jacejsny/

What do you think ?

**Comment by astoilkov** [comment]
Pfuu. This is a hard one for me to decide. I am not sure I understood the second option you described. I see two options:
  1. The first one that you described
  2. All values that are specified as simple non-observable values in the Model definition stay non-observable, all values not specified in the Model definition auto convert to observable values

I really don't know what is best so you could decide implement what you think is best.

**Comment by Kanaye** [comment]
An example of how my 2nd version would work to clarify:

```javascript
var A = App.Model({
  a: blocks.observable(1),
  b: 1
});
var a = new A({b:2, c:1}); 
a.a // => obervable<1>
a.b// => 2
a.c // => 1
```

Hmm I can't really decide either. 
I have to think about that a little more.

**Comment by astoilkov** [comment]
Ok. My second idea is the same. The more I think about it the more it seems to me the second option is better. It is the more expected behavior and it also adds a mechanism to allow for non-observable values in the Model.

I will let you decide. This is my opinion.

**Comment by Kanaye** [comment]
After thinking about this for a bit longer I decided to change it to the second version.
It's more flexible and the user can chose to use properties/obervables themself.
