### ISSUE TITLE
Is jsblocks a node only solution?

### ISSUE THREAD

**Issue by WillRubin** [astoilkov/jsblocks#158]
Pardon, I can't tell from the web site or github. Does jsblocks require node on the server or can I use jsblocks with a server side written in another language w/o needing a node layer in front?

**Comment by Kanaye** [comment]
You only need node if you want to benefit from server-side rendering.
If you are fine with only using jsblocks for client side stuff you can go with a server in any language you wish.

**Comment by Kanaye** [comment]
hi @WillRubin.
I'm closing this issue.
If you have more questions feel free to reopen this issue if it fits the topis  or open an other issue.

Greeting from germany and happy coding.
