### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by derkan** [astoilkov/jsblocks#16]
Hi Antonio, thanks for this elegant framework. Can you show me a quick way to add 

- i18next
- auth checks 

centrally without breaking antyhing?

Regards,
E.D.

**Comment by astoilkov** [comment]
Hi,

I don't have experience with i18next. I have taken a look at what they offer but not sure what you are trying to achieve. Can you be more specific on what you want to achieve with i18next and auth checks so I could help you more effectively.

Thanks for the cooperation.

**Comment by derkan** [comment]
Thanks for quick response. Actually I am looking for a way to add i18 and auth support to jsblocks based sample project. For i18, *I18-next isn't a must*. 

For these features(i18-authendication-authorization) I am studying **jsblocks** framework for adding a support with globally access from both js code and templates. And what I need is best practices for these features. For example, for Auth I am thinking on this way:

- Create a view with integrations(or new development if no external libs will be used) and 
- Extend `App` object and add this view as a property(lets name it: `App.auth`) to be able to access from every module.
- In JS code call `App.auth.has_privilege(priv_name, action)` and continue if returns True else show error. (If not logginned `navigateTo(login)`)
- Extend `blocks.queries` and add a new function as `has_privilege` and use it in templates.
- In templates menu items will be checked to be visible or hidden according to `auth` query result.

Now questions:
- Is it possible to have callbacks on routing centrally?
- Is it possible to access `App` object from templates without adding a variable to `App` object in JS? (Extending `View` object is needed?)

**Comment by astoilkov** [comment]
I will go straight to answering your questions:
 * Currently it is not possible to handle routing globally but there is a reason for that. The idea is to have a View for every main component on the page. So what you can do is define a Main View that have routing and have nested views for childs. Documentation [here](http://jsblocks.com/learn/view-routing-and-history). However, if you give specific case that could not be achieved with the current implementation I am more than willing to implement global routing.
* About the `View` extending you could also refer to [Nested Views](http://jsblocks.com/learn/view-nested-views)
 * Yes. If you are referring to the HTML. You could do this:
```html
<script>
var App = blocks.Application();
App.extend({
  message: 'Hello World'
});
</script>
<div>
  {{message}}

  <!-- or you if you have changed context. $root always points to the Application object -->
  {{$root.message}}
</div>
```

> Additionally, you could always access the same Application object by calling `blocks.Application()`

**Comment by derkan** [comment]
Hi Antonio,

I developed a simple i18n extension for blocks. It is not perfect, developed when I found free time. Please review it.

### Properties
- Automatically downloads lang file.
- Uses message as translation key. By default it accepts language as English.
- Can replace parameters in message
- Caches loaded json lang file.

### Example: 

#### locales/tr.json file is:
```json
{
  "locale": "tr",
  "data": {
    "song {no}": "Şarkı {no}"
  }
}
```
#### Initializing:
```js
    blocks.I18_init({
        lang: 'tr'
    });
```

#### Calling from templates:
```html
<h1>{{ __('song {no}',{ no: 1 }) }}</h1>
```
#### Calling from JS
```js
__('song {no}',{ no: 1 });
```

#### Extension:
```js
    blocks.extend(blocks, {
        _I18n: {
            obsCache: {},
            lngCache: {
                'en': {}
            },
            options: {
                lang: 'en',
                ajax: {
                    async: false,
                    method: 'GET',
                    url: 'locales/{lang}.json'
                }
            },
            load: function (new_val, old_val) {
                blocks.DataSource.prototype._ajax(null, {
                    type: blocks._I18n.options.ajax.method,
                    url: blocks._I18n.options.ajax.url.replace('{lang}', new_val),
                    async: blocks._I18n.options.ajax.async
                }, function (data) {
                    var dt = JSON.parse(data);
                    if (!blocks.has(blocks._I18n.lngCache, new_val)) {
                        blocks._I18n.lngCache[new_val] = {};
                    }
                    blocks._I18n.set_default();
                    blocks.each(dt.data, function (value, key, d) {
                        blocks._I18n.lngCache[new_val][key] = value;
                        if (!blocks.has(blocks._I18n.obsCache, key)) {
                            blocks._I18n.obsCache[key] = blocks.observable(value);
                        } else {
                            blocks._I18n.obsCache[key](value);
                        }
                    });
                });
            },
            set_default: function () {
                blocks.each(blocks._I18n.obsCache, function (value, key, d) {
                    value(undefined);
                });
            },
            set_locale: function (new_locale) {
                blocks._I18n.set_default();
                blocks.each(blocks._I18n.lngset_defaultCache[new_locale], function (value, key, d) {
                    if (!blocks.has(blocks._I18n.obsCache, key)) {
                        blocks._I18n.obsCache[key] = blocks.observable(value);
                    } else {
                        blocks._I18n.obsCache[key](value);
                    }
                });
            },
            translate: function (msg) {
                if (!blocks.has(blocks._I18n.obsCache, msg)) {
                    blocks._I18n.obsCache[msg] = blocks.observable(msg);
                } else if (blocks._I18n.obsCache[msg]() === undefined) {
                    blocks._I18n.obsCache[msg](msg);
                }
                return blocks._I18n.obsCache[msg];
            }
        },
        I18_init: function (options) {
            if (typeof options === 'object') {
                blocks.extend(blocks._I18n.options, options);
            }

            if (blocks._I18n.options.lang != 'en') {
                blocks._I18n.load(blocks._I18n.options.lang);
            }

        },
        I18_locale: function (new_val, old_val) {
            new_val = new_val || 'en';
            if (new_val != 'en') {
                if (blocks.has(blocks._I18n.lngCache, new_val)) {
                    blocks._I18n.set_locale(new_val);
                } else {
                    blocks._I18n.load(new_val, old_val);
                }
            } else {
                blocks._I18n.set_default();
            }
        },
        __: function (msg, params) {
            var res = blocks._I18n.translate(msg)();
            params = params || {};
            blocks.each(params, function (value, key, d) {
                res = res.replace("{" + key + "}", value);
            });
            return res;
        }
    });
    window.__ = blocks.__;
```

**Comment by astoilkov** [comment]
Hmm. That is really interesting. Are you going to use the extension for your own project?

I will just make one suggestion for you. Keep an eye on `blocks.DataSource.prototype._ajax` override because I am planning on refactoring some of the code. I will also make an external method that can make ajax calls. I can write in this thread when this happens.

Additionally, have you thought of extending the `blocks.observable()` as described in [this](http://jsblocks.com/learn/working-with-observables-extending-observable-functionality) article. This way it will be possible to do something like this:

```javascript
blocks.observable.I18 = function () {
  // your implementation here
};

// this way message could be used more easily
var message = blocks.observable('your message').extend('I18');
```

**Comment by derkan** [comment]
Yes, I will use it. And commented and refactored the code and put in @derkan/jsblocks.I18n
Will update code after you add ajax function.
Again thanks again for this elegant framework.

**Comment by astoilkov** [comment]
Perfect. I am glad that you like the framework. I am closing this one. Reopen or open a new one if needed.
