### ISSUE TITLE
chaining reduce produces different results than static method.

### ISSUE THREAD

**Issue by jdalton** [astoilkov/jsblocks#17]
I noticed the chaining `reduce` is one off of the non-chaining version. For reference see the current micro-benchmark we've discussed.

**Comment by astoilkov** [comment]
Yes. Thanks. I will look at it.

**Comment by astoilkov** [comment]
I have created a separate [issue](https://github.com/astoilkov/jsblocks/issues/53) for removing the utility methods from jsblocks and leave the work to libraries like lodash and underscore. I am closing this one and copying the issue to the jsvalue repo (which is currently private repository).
