### ISSUE TITLE
Setting up an observable with an initial null value throws an error

### ISSUE THREAD

**Issue by walterdavis** [astoilkov/jsblocks#18]
~~~js
  function Model(){
    this.user_input = blocks.observable();
    this.headline = 'Howdy from the application';
  }
  blocks.query(new Model());
~~~
~~~html
  <h1>{{headline}}</h1>
  <input data-query="val(user_input)" placeholder="Enter some text…" size="40"/> <button class="clear">&times;</button>
  <p>{{user_input}}</p>
~~~

This works, but it throws an error unless I declare a global variable named user_input. If I put an initial value in like blocks.observable('foo'), then I don't get the error, but I also can't use a placeholder as I would like. I would like the variable to initialize to an empty string if nothing is passed into it by observable.

**Comment by astoilkov** [comment]
Hmm. Interesting. I have created a [jsfiddle example](https://jsfiddle.net/27ovr82e/) that I have tried to replicate the problem but with no success. Can you try to replicate it in the jsfiddle example and show me what I am missing.

Thanks in advance.

**Comment by walterdavis** [comment]
I found that it did not fail here either in the cut-down example I provided (should have tested that before I submitted). But adding one more block to the script did make it fail https://jsfiddle.net/27ovr82e/2/

Is this incorrect, syntax-wise? Should I have these two things combined in some manner?

Walter

**Comment by astoilkov** [comment]
I couldn't break the example when I opened it maybe its browser specific. Howerver, this does not matter a lot because you should not combine(and there is no reason to) combine `blocks.Application()` and `blocks.query()`. You should use one but now both together. What best suit your needs. The Application gives more structure to your application and the `blocks.query()` gives you more freedom.

**Comment by walterdavis** [comment]
Okay. Thanks. Just feeling my way into this system, haven't used any other framework yet. Perhaps a non-trivial example app would help me see how to do more than one thing at a time.

**Comment by astoilkov** [comment]
Did you check out the [jsblocks shopping example](https://github.com/astoilkov/jsblocks-shopping-example) which is a full application implementation that you can learn a lot from.

![jsblocks-shopping-example](https://cloud.githubusercontent.com/assets/884810/7434372/1d88b378-f043-11e4-8269-b17a171b4f30.png)

**Comment by walterdavis** [comment]
I saw that right after I pressed send. Sorry for the noise, that is a very complete example. And after I un-f***d my npm install, it worked perfectly and looks great.

Thanks again,

Walter
