### ISSUE TITLE
Can an observable respond to external script events?

### ISSUE THREAD

**Issue by walterdavis** [astoilkov/jsblocks#19]
I want to create a clear button for a text field that is being observed. It works, from the standpoint that the button clears the content of the field. But the two-way binding is not updated when this happens. Is there either an internal way to change the bound value, or an event I can fire that will wake up the binding to the new value?

**Comment by astoilkov** [comment]
I have implemented the behavior based on your code from the previous issue. Take a look [here](https://jsfiddle.net/27ovr82e/1/).

```html
<button data-query="click(clearValue)" class="clear">&times;</button>
```

```javascript
this.clearValue = function () {
  userInput('');
};
```

**Comment by walterdavis** [comment]
This doesn't seem to work here (maybe I put it together wrong). The binding works, typing in the form field does make the P tag change. But clicking the button does not do anything to either the content of the field or the P tag that mirrors it. Example here: https://jsfiddle.net/m4jms7z1/

**Comment by astoilkov** [comment]
Actually you have forgotten to declare the `user_input` variable so it could be accessed in the function:

```javascript
var user_input = this.user_input = blocks.observable();
```

**Comment by walterdavis** [comment]
Thanks, that fixed it.
