### ISSUE TITLE
Possible error in React perf test

### ISSUE THREAD

**Issue by Termina1** [astoilkov/jsblocks#21]
Hi, I noticed this code in ```syncing-changes/react.html```

```javascript
var data = generateData(500);
var columns = getColumns();
React.render(
        React.createElement(Table, {people: data, columns: columns}),
        document.getElementById('example')
);
```

And for ```syncing-changes/blocks.html```

```javascript
var items = blocks.observable(generateData(100));
blocks.query({
    items: items,
    columns: getColumns()
});
```

Is this a typo? Seems a bit unfair. After correcting first example to 100, results became indistinguishable for me.

**Comment by astoilkov** [comment]
Hi. Yeah you are correct it is a type. However, I have really great news. I have been hard working on implementing the new performance improvements and they are early stage but I want to share them with you so you will see the performance differences. You could download the project containing the new version of jsblocks from [here](https://dl.dropboxusercontent.com/u/4277603/performance_improvements.zip) and run the samples again.

Let me know who it goes. :)

**Comment by astoilkov** [comment]
I have committed the [performance improvements](https://github.com/astoilkov/jsblocks/commit/5254b4afb58ac48f8f53982dff85800704e7bced) and updated the .zip file that you download from the official website.

I am closing this one. Feel free to reopen this issue or open a new one.
