### ISSUE TITLE
RxJS

### ISSUE THREAD

**Issue by xgrommx** [astoilkov/jsblocks#22]
Hello @astoilkov. Can I use RxJS or another similar library with jsblock observable together?

**Comment by astoilkov** [comment]
Hi,

There is no built-in way for dealing with RxJS or any other library. However, I think you could use RxJS with jsblocks observables. What I can imagine is that you will need to sync both collections at some point (when you need to update the changes in the dom).

You could try it out and write about your experience in this thread so it will be useful for other developers. :)

**Comment by msegundo** [comment]
Hi, good question. I am interested on that too, let's try to do it.

**Comment by astoilkov** [comment]
Hey guys. Any update on that? If none I will close this one in couple of days.

**Comment by astoilkov** [comment]
I am closing this one. If you have any updates on that - reopen it.
