### ISSUE TITLE
How to init jquery plugins after view is mounted to DOM?

### ISSUE THREAD

**Issue by derkan** [astoilkov/jsblocks#23]
Hi Antonio,
I have to init some jquery plugins after the view(and its template) is mounted to DOM. I tried view's `routed` callback but it seems this callback is too early for this task. I can only do initialization of plugins by waiting in `setTimeout`. Is there a better way?
Regards,

**Comment by astoilkov** [comment]
There is a `ready` callback that I have not documented yet but it exists.
```javascript
App.View('MyView', {
  ready: function () {
    // the dom is ready. Initialize your plugin
  }
});
```

> I will document it write away

**Comment by derkan** [comment]
Thanks!
