### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by bebraw** [astoilkov/jsblocks#24]
Your site (http://jsblocks.com/) doesn't appear to work at the moment.

**Comment by astoilkov** [comment]
Sorry for that. I have fixed the problem.

**Comment by bebraw** [comment]
No worries. I noticed this after [an automated tweet](https://twitter.com/jsterlibs/status/598533172150697985) went up.

It could be a good idea to set up [website-poller](https://pypi.python.org/pypi/website-poller), Pingdom or something.
