### ISSUE TITLE
How can I use with slim php Thanks

### ISSUE THREAD

**Issue by Danjavia** [astoilkov/jsblocks#27]

**Comment by astoilkov** [comment]
Hi,

In what you are interested in specifically? I can tell you my experience using PHP to build [Hmm](https://web.hmmapp.com/) web prototype. jsblocks could be used the same way as any JavaScript framework.

Hmm was initially using jQuery and we migrated it to jsblocks. What it seems to be a bad practice is to include PHP in your `data-query` attributes. Instead you could define the needed data in JavaScript variables that would be passed using PHP. Additionally, working with remote data could be a little harder if you want to initially load it with PHP and then update the data using jsblocks Collection.

In general using jsblocks in pure HTML scenario or using PHP should not differ a lot. However, if you have specific question I will be glad to help you out.

**Comment by Danjavia** [comment]
I need send data to the server and viceverse. What is the best way for this?

**Comment by astoilkov** [comment]
It depends what kind of data you are sending. You could take a look at the articles below which describe how to work with remote data:
 * If you want to send an array of data you could use [Collection](http://jsblocks.com/learn/collection-plug-in-a-service)
 * If you want to send single item of data you could use the [Model](http://jsblocks.com/learn/model-plug-in-a-service)

Note that both the Collection and Model have the same settings and you could specify read, update, destroy and create operations on both of them. You could try using these and if you have any problems do not hesitate to write back. :)

**Comment by Danjavia** [comment]
Ok perfect thanks. Sorry how can I manage vents in jsBlocks e.g. click, mouseover etc.

**Comment by astoilkov** [comment]
You could take a look at the help article below:
 * [Event queries](http://jsblocks.com/learn/queries-event-queries)

The idea behind them is to use the built-in events or a the on() query if there is no built-on:
```html
<a data-query="click(callback).on('custom-event', callback)"></a>
```

**Comment by Danjavia** [comment]
Thanks @astoilkov
