### ISSUE TITLE
How can I add items dinamically e.g. using add user button

### ISSUE THREAD

**Issue by Danjavia** [astoilkov/jsblocks#29]

**Comment by astoilkov** [comment]
Dynamically adding items is easy when you use observables. Observables could be used as regular arrays. You could take a look at the last example on the [home page](http://jsblocks.com). The main idea is creating an observable and pushing a new value in the array when click handler is called.

```html
<button data-query="click(addItem)">Add Item</button>
```

```javascript
var items = blocks.observable([]);

function addItem() {
  items.push('new item');
}
```

**Comment by Danjavia** [comment]
That's perfect. Now, I can set data-query="val(url)" over it's elements and how print the result in other div. if this has been created dinamically.

**Comment by astoilkov** [comment]
I am not sure I understand you correctly. You could set the HTML of an element using html() data query.

```html
<div data-query="html(url)"></div>
```

Additionally, if you want to print a custom formatted string you could use dependency observable for that:

```javascript
var data = blocks.observable([1, 2, 3]);

var result = blocks.observable(function () {
  return data.join(' - ');
});
```

If I didn't understand you correctly do not hesitate to correct me.

**Comment by Danjavia** [comment]
No, This is my code

    blocks.query({
        name: blocks.observable(),
        description: blocks.observable(),
		urls: [],
        clicked: function (e) {
        	e.preventDefault();
		    // this points to the model
		    $( this.clickCount ).insertBefore( '.button.new' );
		    this.urls.push( 'dante' );
		},

		clickCount: '<div class="ui icon input">'
				+ '<input type="text" placeholder="Insert URL" data-query="val(url)" autofocus>'
				+ '<i class="browser icon"></i>'
			+ '</div>'
			+ '<div class="ui inverted divider"></div>',

		url: blocks.observable(),
    });

I need to read the value of url after the inputs has created and drw it value in other div?

Thanks for ur help!

**Comment by astoilkov** [comment]
Now I understand. I have created a [JSFiddle example](https://jsfiddle.net/17gaqydh/) showcasing the desired behavior. The key is to use `template()` data-query.

```html
<div data-query="template(clickCount)"></div>

<div data-query="html(url)"></div>
```

**Comment by Danjavia** [comment]
This is the issue exactly 

https://jsfiddle.net/k8yjwmpk/

Sorry! thanks for ur help again!

**Comment by astoilkov** [comment]
I modified the provided example. It now you could add items to the collection. However, I didn't find logic in the replacing of HTML so I removed it. If you have some idea behind it you could explain it and I will help you implement it.

**Comment by Danjavia** [comment]
The idea create a list and insert items within and print a preview of the list with their items .

https://jsfiddle.net/6w73u543/

**Comment by astoilkov** [comment]
Sorry but I don't understand what you are trying to achieve. Could you create a sample HTML of the result after inserting the third item? If I see what the HTML should look like in the end I could help you.

Thanks for your cooperation in advance.

**Comment by Danjavia** [comment]
![scrfeenshot](https://cloud.githubusercontent.com/assets/1041322/7800897/02c6e1f2-02e2-11e5-9d60-3a2671b97bb6.png)

**Comment by Danjavia** [comment]
Thanks 4 help!

**Comment by astoilkov** [comment]
Sorry for the late response. I will implement it and send you the example. :)

**Comment by astoilkov** [comment]
I have implement the example. Take a look and see if this is what you are looking for.
[https://jsfiddle.net/6w73u543/1/](https://jsfiddle.net/6w73u543/1/)

**Comment by Danjavia** [comment]
Hi @astoilkov Your the best guy!! Really thanks. I will to implement this in my code. Thanks again!

**Comment by astoilkov** [comment]
Happy to hear that. Closing this one.
