### ISSUE TITLE
Enable CSP mode, so jblocks can be used in Chrome extensions

### ISSUE THREAD

**Issue by naturalist** [astoilkov/jsblocks#30]
Chrome extensions do not allow code generation from strings. The John Doe example errs with
```
Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' chrome-extension-resource:".
```
Consider adding CSP mode in the future.

**Comment by astoilkov** [comment]
Hmm. How do you imagine that. Can you provide a little more information?

**Comment by naturalist** [comment]
Honestly, I don't know exactly how it works, but Angular implements it. Take a look at https://docs.angularjs.org/api/ng/directive/ngCsp#!

**Comment by astoilkov** [comment]
I just saw the AngularJS implementation. However, they implement manual parsing of the code which takes about thousand and more lines of code. Maybe someone could create a plugin for this but I don't think the place of such code is in the framework itself.

For now I am closing this one. However, I will take this into account if I have time to implement such a plugin. Sorry for not being able to use jsblocks in Chrome Extension Development it would have been great. :)
