### ISSUE TITLE
Creating Records in Collections has no Request Payload

### ISSUE THREAD

**Issue by cybrox** [astoilkov/jsblocks#33]
I have tried writing an application that is hooked up to a server, basically it was creating a record as stated [in the documentation](http://jsblocks.com/learn/model-plug-in-a-service), and combined that with the Collection/List approach.

The problem is, when I run the code that is presented in the documentation, it - obviously - works. If I embed this code in something similar to the list example on [the homepage](http://jsblocks.com/), it doesn't sync correctly. So I went back to the `Cake` test script and tried to reproduce it using the following code:

```js
        var App = blocks.Application();

        var Cake = App.Model({
            cakeType: blocks.observable(),
            cakeSize: blocks.observable(),

            fullCake: function(self) {
                return self.cakeType() + 'cake (' + self.cakeSize() + ')';
            },
        })

        var Cakes = App.Collection(Cake);

        App.View('Bakery', {
            newCake: Cake(),

            cakes: Cakes([
                { cakeType: 'strawberry', cakeSize: 'small' },
                { cakeType: 'chocolate', cakeSize: 'large' }
            ]),

            bakeCake: function() {
                this.cakes.add(this.newCake);

                console.log(this.newCake.cakeType()); // TEST OUTPUT
                this.newCake.sync();
                this.newCake.reset();
            }
        });
```
```html
    <div data-query="view(Bakery)">
        <div>
            <h2>Let's eat some, {{newCake.fullCake(newCake)}}!</h2>
            Type: <input data-query="val(newCake.cakeType)" />
            <br />
            Size: <input data-query="val(newCake.cakeSize)" />
            <button data-query="click(bakeCake)">Bake!</button>
        </div>
    </div>
```

The problem is, while the request to the respective `create url` - which isn't given in this example but it doesn't make a difference - is successfully sent, it does not contain any request payload. So I'm basically sending an empty payload to the server.
Loggin the data via `console.log` at the "TEST OUTPUT" does show, that the Model actually contains data but it's not serialized and packed into the request.

**Comment by astoilkov** [comment]
In order to make this work you will have to use `App.Property()`. This tells the framework that the property is part of your service and it needs to be sent. This allows you to create properties that are send to the service and others that only contain metadata.

```javascript
var Cake = App.Model({
    cakeType: App.Property(),
    cakeSize: App.Property(),

    fullCake: function(self) {
        return self.cakeType() + 'cake (' + self.cakeSize() + ')';
    }
});
```

**Comment by astoilkov** [comment]
Note that `App.Property` is actually an observable. You could read more about it [here](http://jsblocks.com/learn/property-introduction).

**Comment by astoilkov** [comment]
I am closing this one. If you have any additional questions do not hesitate to open a new issue.

**Comment by cybrox** [comment]
Oops, I totally forgot to reply to this.
Thanks for the hint, that actually solved the problem. Though, from what I can see, the docs page you linked, as well as the docs for properties does not explicitly show the difference here. Maybe I have just overlooked it, anyways, I think it might be worth adding a note [here](http://jsblocks.com/learn/model-plug-in-a-service) as well, or explicitly state out the difference somewhere in the doc *Model* intro.

In general, while the docs have nice examples, I personally think they could need some additional descriptions for things, but I guess that'll improve over time :smile:

**Comment by astoilkov** [comment]
Yes. I agree with you. The docs need more work. And Yes this will improve over time. The Model Plug in a service has to be a lot more descriptive. I am going to fix this.

Thanks for the feedback.
