### ISSUE TITLE
Error on remove item in collection (removeAt)

### ISSUE THREAD

**Issue by froilanq** [astoilkov/jsblocks#34]
Error: 

TypeError: ElementsData.data(...) is undefined --> blocks.js (línea 10115, col 21)

**Comment by astoilkov** [comment]
Hi.

Could you give a snippet of code on how you reproduced the error? I have tried to reproduce it but without success.

**Comment by froilanq** [comment]
I reviewed the code found my mistake, thanks for the reply. Thank.
