### ISSUE TITLE
jsblocks and hybrid mobile app

### ISSUE THREAD

**Issue by pcdinh** [astoilkov/jsblocks#35]
Hi,

I am exploring possibility to use jsblocks and materializecss in an Android app (using Crosswalk to boost performance). Is there any limitation that I need to know? I understand right now that jsblocks can be used for both web and hybrid mobile app (as in Ionic or OnSen UI). However I don't know if it works well with Cordova/Phonegap or not. My feeling is that I can integrate 2 JS framework together without any issue because there is no conflict in architecture.

Thanks 

Dinh

**Comment by astoilkov** [comment]
Hi Dinh,

Yes. jsblocks could be used for web, hybrid mobile apps for desktop applications. However, I have tried using it in web and desktop applications and never under mobile. This is why I could not pinpoint limitations. In general there should be no problems but I could not guarantee you. My experience for desktop applications was great.

You could try it and share your experience. I am ready to fix issues.

**Comment by astoilkov** [comment]
I am closing this one. If you have any additional questions please do not hesitate to reopen this issue or open a new one.
