### ISSUE TITLE
updates in view from other frameworks

### ISSUE THREAD

**Issue by Jir0** [astoilkov/jsblocks#38]
I'm trying to combine jsblock with websockets using socket.io, however I can't figure out how to update a view from outside (from the callback of the socket) any ideas on how to get about this?

EDIT: I forgot to include to code I'm using

```javascript
'use strict';
var App = blocks.Application();

var Message = App.Model({
	author: App.Property({
		defaultValue: 'anonymous'
	}),
	message: blocks.observable()
});

var Messages = App.Collection(Message, {
	even: blocks.observable(function () {
		return this().length % 2 == 0;
	})
});

App.View('Chat', {
	
	name: 'Wannes Gennar',
	newMessage: Message(),

	init: function () {
		this.socket = io('http://localhost:3000');
		this.messages = Messages();
		
		var service = this;
		console.log(service);
		
		this.socket.on('chat message', function (msg) {
			service.messages.push({
				message: msg
			});
		});
	},

	addMessage: function () {

		this.socket.emit('chat message', { author: this.newMessage.author, message: this.newMessage.message });
		this.newMessage.reset();
	},
	
	up: function(e)
	{
		if (e.which === 13)
			this.addMessage();
	}
});
```

**Comment by astoilkov** [comment]
Hi,

Hmm. The code seems correct. Does the provided implementation work? Is there any error being thrown? Are you sure the socket handler is called?

Thanks in advance.

**Comment by Jir0** [comment]
the given implementation threw the error 'messages not defined', however this was easily fixed using
```javascript
this.socket.on('chat message', function (msg) {
service.messages().push({
    message: msg
});
});
```
however although it doesn't throw errors, it doesn't seem to update. I confirmed that the websocket handler works by debug printing it. Any ideas?

**Comment by astoilkov** [comment]
Ok. Now I see the problem. You are unwrapping the messages observable. In order to fix the problem you should call `push()` on the `Collection` object not on the `Array` object.

```javascript
this.socket.on('chat message', function (msg) {
  // instead of service.messages()
  service.messages.push({
    message: msg
  });
});
```

**Comment by Jir0** [comment]
using the code you gave me gives me 'messages not defined' error,
![see here](https://cloud.githubusercontent.com/assets/2164354/7897520/bf0e7384-06de-11e5-9a47-c91dc2bd3df9.png)

**Comment by astoilkov** [comment]
Hmm. It is possible that you have not defined your HTML correctly. I have created an example in jsfiddle [here](https://jsfiddle.net/swk02o89/) so you could take a look at it and compare it with your HTML. I have replaced the socket.io functionality with another handler.

**Comment by Jir0** [comment]
I just tried renaming messages to history and for some reason now everything works perfectly fine. Do you have an idea why this could be?

**Comment by astoilkov** [comment]
Can you also provide your HTML so I can take a look at it and try to understand why this was happening?

**Comment by Jir0** [comment]
I tried making a jsfiddle but as horrible with it as I am I'm just gonna paste the HTML here, it's not that much anyway

```html
		<div class="ui page grid">
			<div class="sixteen wide column">
				<h1>Chat app</h1>
				<div class="ui card" data-query="view(Chat)">
					<div class="content">
						<div class="header">{{ name }}</div>
						<div class="description" data-query="each(history)">
							<div class="ui floated compact primary segment" data-query="setClass('right', history.even).setClass('left', !history.even)">
								<p>{{ message }}</p>
							</div>
						</div>
					</div>
					<div class="extra content">
						<div class="ui transparent input">
							<input data-query="keyup(up)" type="text" placeholder="Message...">
						</div>
					</div>
				</div>
			</div>
		</div>
```

note that this is after renaming 'messages' to 'history' and it seems to work

**Comment by astoilkov** [comment]
This is super strange. I have no idea why this have happened. If you want to know why this have happened(like I do) you could create a simple project that replicates the problem and send it to me I will debug it and pinpoint the exact cause of the issue.

**Comment by Jir0** [comment]
the project we're speaking off is a very small toy project, shall I just zip it and send it over?

**Comment by astoilkov** [comment]
Yeah. Absolutely.

**Comment by astoilkov** [comment]
Thanks for sending me the project. Now I get it. The reason was the `data-query` in the `div` was failing because there wasn't messages defined there because in `each` query the context changes.

```html
<div class="ui floated compact primary segment" data-query="setClass('right', messages.even).setClass('left', !messages.even)">
```

Instead the `div` data-query should access the parent context:

```html
<div class="ui floated compact primary segment" data-query="setClass('right', $parent.messages.even).setClass('left', !$parent.messages.even)">
```

The reason why history is working is because there is window.history global object that you are accessing.

I hope I was clear enough. If not I can try and explain it again. :)

**Comment by Jir0** [comment]
no that was clear, thanks a lot. Seems I still have a long road ahead but jsblocks seems worth it. Keep up the good work!

**Comment by astoilkov** [comment]
Happy hearing that. I am closing this one. If you have additional questions open a new one or join [Gitter](https://gitter.im/astoilkov/jsblocks?utm_source=github_link) and ask there. :)
