### ISSUE TITLE
Reported err

### ISSUE THREAD

**Issue by webcliq** [astoilkov/jsblocks#39]

**Comment by webcliq** [comment]
On loading a project with jsblocks, Firebug reports 20 or so unreachable code blocks after a return

**Comment by astoilkov** [comment]
Hi,

Can you provide a little more context on that. Can you show the code that is causing this? Can you show a screenshot of the Firebug errors?

**Comment by webcliq** [comment]
Understood. I will do. I will also setup a minimal system with only necessary code to ensure that I can replicate the issue on the most minimum system possible. Expect activity within a day or two.

This is just a simple example of the problem. In my web sites and programming activities. I follow a method where by all JS libraries and scripts are integrated into one file and the file is loaded and executed before close Body.

For the purpose of this example. I removed all my scripts from Cliqon.Js leaving only Blocks.Min.Js as downloaded yesterday.

I have a number of strategic and practical reasons why I would wish to use your Jsblocks instead of Backbone or Knockout, for example. However as a Developer myself, it is essential that I replicate the issue that I am seeing in an environment as close to that which you have designed and envisaged as possible.

GET http://dev.ojored.com/ [HTTP/1.1 200 OK 133ms]
GET http://dev.ojored.com/views/css/style.css [HTTP/1.1 304 Not Modified 2ms]
GET http://dev.ojored.com/views/js/loader.js [HTTP/1.1 304 Not Modified 3ms]
GET http://dev.ojored.com/views/css/bootstrap.css [HTTP/1.1 304 Not Modified 1ms]
GET https://fonts.googleapis.com/css [HTTP/2.0 200 OK 454ms]
GET http://dev.ojored.com/views/js/cliqon.js [HTTP/1.1 200 OK 12ms]
SyntaxError: unreachable code after return statement cliqon.js:1:2291
SyntaxError: unreachable code after return statement cliqon.js:1:4046
SyntaxError: unreachable code after return statement cliqon.js:1:4532
.........
.........
SyntaxError: unreachable code after return statement cliqon.js line 3 > Function:1:6687
SyntaxError: unreachable code after return statement cliqon.js line 3 > Function:1:7134
SyntaxError: unreachable code after return statement cliqon.js line 3 > Function:1:7623
SyntaxError: unreachable code after return statement cliqon.js line 3 > Function:1:8319
SyntaxError: unreachable code after return statement cliqon.js:1:167

**Comment by astoilkov** [comment]
I can't understand why the error is happening. Isolating the problem and sending it would be of great help.

Thanks in advance.

**Comment by webcliq** [comment]
I am going to use your Gmail Address so that I can send you an explanation of my findings plus some files.

**Comment by astoilkov** [comment]
I received the email and reply to you because I didn't succeeded in replicating the problem. You could take a look at the email and let me know what was the result.

**Comment by webcliq** [comment]
Dear Antonio,

I will, test out what you sent back.

I will also replicate my Test on my Production webserver and see if I
get the same problem. If I do, I can then offer two opportunities -
you will be able to access my Test and I can also give you remote
access to my production web server for you to find out what is going
on.

It will be a few days before I can do all of this.

---------------------------------------------
Mark Richards
Conkas
Email: mark.richards@conkas.com
Mobile: +34 650 704 745
--------------------------------------------

On Thursday, 04-06-2015 at 12:56 Antonio Stoilkov wrote:




I received the email and reply to you because I didn't succeeded in
replicating the problem. You could take a look at the email and let me
know what was the result.



—
Reply to this email directly or view it on GitHub [1].

  





Links:
------
[1]
https://github.com/astoilkov/jsblocks/issues/39#issuecomment-108839600

**Comment by Kanaye** [comment]
These "SyntaxError: unreachable code after return statement "-messages are warnings and even if Firefox calls them "SyntaxError" these are not stopping execution of code or anything.
It's a known issue of Firefox js-engine to throw these warnings in some ``new Function``-calls.
In this case it's [this call](https://github.com/astoilkov/jsblocks/blob/9f12d66e5c99cf33bbecdb6017a777fa838b058b/lib/blocks/value-nocore.js#L1299-L1304) in jsvalue. Unfortunately I can not find the bugzilla where this is discussed (there are to many with this topic).
In my opinion this issue can be closed, as this is not restricting code execution and as there is the plan to remove jsvalue from jsblocks (#53).

**Comment by astoilkov** [comment]
Wow. Nice. I didn't know that. Ok I agree. We can close this issue.
