### ISSUE TITLE
view inside each

### ISSUE THREAD

**Issue by iamphill** [astoilkov/jsblocks#43]
Trying to add a view with a separate HTML file and it comes back with the error..

```
Critical: view(Row) - exception thrown while executing query parameter   <li data-query="view(Row)" data-id="20">
```

Is this not possible?

**Comment by astoilkov** [comment]
My guess is that you have changed the context and the `Row View` is not accessible. Try this:

```html
<li data-query="view($root.Row)" data-id="20">
```

`$root` points to the `Application` object where the Row is probably created. You could learn more about contexts [here](http://jsblocks.com/learn/syntax-context-properties).

**Comment by iamphill** [comment]
@astoilkov Works perfectly thanks!
