### ISSUE TITLE
{{expressions}} syntax conflicts when using with some other templates

### ISSUE THREAD

**Issue by panzhangwang** [astoilkov/jsblocks#46]
I want to use jsblocks within swig[https://github.com/paularmstrong/swig]. Apparently, {{}} is used for expressions in both.

**Comment by astoilkov** [comment]
Hi,

Do you use it on the server or on the client? I have been using Handlebars on the server and jsblocks on the client I had succedded by escaping the Handlebar templates placing a `\` in front of every expression I wanted jsblocks to execute. This could help you with swig.

Does swig have a way to make the expression syntax custom and not use the `{{ }}` syntax? This way there wouldn't be a conflict between the two.

Additionally, where do you use swig where jsblocks couldn't be used? Maybe it is possible to use only jsblocks.

**Comment by panzhangwang** [comment]
Thanks. I like the idea to use the template on the server and jsblocks on the client.

**Comment by astoilkov** [comment]
Perfect. Try it out and let me know if it helps.

**Comment by astoilkov** [comment]
I am closing this one. If you have problems with the solution do not hesitate to write here and I will reopen the issue.
