### ISSUE TITLE
chaining with each is not skipping the function passed to each

### ISSUE THREAD

**Issue by atondelier** [astoilkov/jsblocks#47]
Compiling a chain into a raw callback composition is a very good idea. As of now, there are some bugs with it.

An exemple is better than long explanations. The following code:
```JS
blocks([0,1,2])
.each(function(v) { console.log('first each', v); })
.each(function(v) { console.log('second each', v); })
.map(function(v) { console.log('first map', v); return v; })
.map(function(v) { console.log('second map', v); return v; })
.value();
```

is logging this:
```
first each 0
first each 1
first each 2
first each 0
second each 0
first each 1
second each 1
first each 2
second each 2
first each 0
second each 0
first map 0
second map 0
first each 1
second each 1
first map 1
second map 1
first each 2
second each 2
first map 2
second map 2
```

We see 2 things:
 - the second "each" is recalling the first one
 - the 2 cleverly composed "map" are recalling both "each"

**Comment by astoilkov** [comment]
I am in a progress of deciding to remove the built-in utility library and switch to using Lodash instead. The current implementation is not stable enough and I don't see a benefit of using it when comparing it to Lodash. I will release the library as an individual project. If it becomes more stable I could then include it in jsblocks.

What do you think?

**Comment by astoilkov** [comment]
I have created a separate [issue](https://github.com/astoilkov/jsblocks/issues/53) that will do what I told you. I am closing this one and copying the issue to the jsvalue repo (which is currently private repository).
