### ISSUE TITLE
ZURB Foundation compatibility issue

### ISSUE THREAD

**Issue by aztec8** [astoilkov/jsblocks#50]
Hey guys, I'm trying to use Zurb Foundation with my jsblocks app but it doesn't seem to be working. 

I added some console.logs() to Foundation's init function and confirmed that it is being called.

**Comment by astoilkov** [comment]
Hi,

Can you provide a little running demo showcasing the problem so I could debug it?

Thanks for the cooperation in advance.

**Comment by aztec8** [comment]
Sure thing, my repo is here:
https://github.com/aztec8/jsblocks-seed


There should be a [Foundation Joyride](http://foundation.zurb.com/docs/components/joyride.html) when a new user views the page. 

Also, if you click on "Product" in the sidebar and try to change between the Description and Image tabs it doesn't work. Although if you click around between "Hello World", the "Parlec Parts Resource" (in the header), and then go back to "Product" the tabs work as expected. If you load the /product url directly the tabs don't work however.

Thanks for your help

**Comment by astoilkov** [comment]
You correctly found that the foundation framework should reflow after the page have been loaded. The problem is that the method you were searching for is not part of the API documentation. You need the `ready` callback described [here](https://github.com/astoilkov/jsblocks/blob/master/src/mvc/View.js#L71-87). The `routed` method is called to early.

I will add the method in the API documentation.

```javascript
// product page
App.View('product_page', {
    options: {
        route: '/product',
        url: 'views/_product-page.html'
    },

    ready: function () {
      $(document).foundation('tab', 'reflow');
    }
});
```

**Comment by aztec8** [comment]
Gotcha. Thanks for your help! 

Would you recommend this approach going forward? Firing off foundation as needed per page?

**Comment by astoilkov** [comment]
Yeah. Absolutely. I use this approach for [http://jsblocks.com](http://jsblocks.com). This method is specifically created for such scenarios.
