### ISSUE TITLE
Custom query update function is not called

### ISSUE THREAD

**Issue by mstdokumaci** [astoilkov/jsblocks#54]
I'm trying this example: http://jsblocks.com/learn/queries-creating-a-custom-query

It doesn't work as expected.

It works when I add a line "blocks.query({})" before example.

Try yourself:
http://codepen.io/anon/pen/oXeVQe

**Comment by astoilkov** [comment]
Hi @mstdokumaci,

Yes. This is expected. If you want your `data-query` attributes to be executed you will always need to call `blocks.query()` or create a `blocks.Application()` instance. Creating custom query instructs jsblocks to have additional methods for execution but does not force them to get executed.

**Comment by mstdokumaci** [comment]
Understood. Thanks for quick response.
