### ISSUE TITLE
As would the use of templates recursively

### ISSUE THREAD

**Issue by froilanq** [astoilkov/jsblocks#55]
As would the use of templates recursively, see example:

JS: 
```
var Menus = blocks.observable([{label: 'test1', menu: [{label: 'sub_test1', menu:[]}]}, {label: 'test2', menu: []}, {label: 'test3', menu: []}]);
```

HTML:
```
<script id="item_menu" type="text/blocks-template">
	<div data-query="each($this)">
		<h3>{{label}}</h3>
		<p>{{menu.length}}</p>
		<div data-query="visible(menu.length > 0).template('item_menu', menu)"></div>
	</div>
</script>
<div data-query="template('item_menu', Menus)"></div>
```

RESULT:
```
test1
1
{{label}}
{{menu.length}}
test2
0
test3
0
```

**Comment by astoilkov** [comment]
Hi @froilanq,

I have been investigating this and found the problem. I have found a solution and will need to test it for little longer to ensure stable change. I will update you when I am ready. Thanks for reporting this issue.

**Comment by froilanq** [comment]
Thanks, I'll be careful, to be implemented in my projects.

**Comment by mansurg** [comment]
@astoilkov thank you!

**Comment by froilanq** [comment]
Yes it works correctly, thank you.

**Comment by astoilkov** [comment]
Happy to help. :)
