### ISSUE TITLE
CommonJS

### ISSUE THREAD

**Issue by zombiQWERTY** [astoilkov/jsblocks#59]
Is JSBlocks working with CommonJs libraries like Browserify?

**Comment by astoilkov** [comment]
Yes. It does support them. It uses the same approach as jQuery for exposing it globally.

**Comment by zombiQWERTY** [comment]
I tried to use Browserify with JSBlocks, but it caught an error

**Comment by astoilkov** [comment]
I will try doing it to see what happens. Can you send me the error?

**Comment by zombiQWERTY** [comment]
One second, I'm repairing the situation now

**Comment by zombiQWERTY** [comment]
I'm sorry so much...
But I tried to do like that:
JB = require "blocks"
instead of:
JB = require "blocks/blocks.js"

Closed

**Comment by astoilkov** [comment]
Happy everything works fine. Happy coding. :)

**Comment by zombiQWERTY** [comment]
You too =)
