### ISSUE TITLE
from / to JS

### ISSUE THREAD

**Issue by MikeBild** [astoilkov/jsblocks#6]
Is it possible to convert a JS object to an observable / observableArray? Each object should, of course, an observable object.

e.g.
var array = [{foo:'bar},{bar:'foo'}];
var observableArrayWithObservables = blocks.toObservable(array);

**Comment by astoilkov** [comment]
Just write:

blocks.observable(array);

**Comment by astoilkov** [comment]
This will create an observable with the array values inside of them. In order to access the array you could do:

var observable = blocks.observable(array);

var array = observable();

You could add values to the array by doing:

observable.push(value);

**Comment by MikeBild** [comment]
thank you!
