### ISSUE TITLE
Can't get current route

### ISSUE THREAD

**Issue by zombiQWERTY** [astoilkov/jsblocks#60]
I think its's a bug
Here is console.log options of view
http://s16.postimg.org/3jq57zdyd/image.png

**Comment by zombiQWERTY** [comment]
Current route "type" has "test" value

**Comment by astoilkov** [comment]
I am not sure I understood you correctly. The `view.options` are not dynamically populated. If you want to catch the current route you could subscribe to the view `routed()` method where the arguments are passed when the View has been routed.
