### ISSUE TITLE
strange behaviour of observable array

### ISSUE THREAD

**Issue by oncesk** [astoilkov/jsblocks#66]
```javascript
var data = blocks.observable([
	{
		title : 'One',
		nested : [
			1,
			2,
			3
		]
	},
	{
		title : 'Two',
		nested : [
			111,
			222,
			333
		]
	}
]);

App.View('Contact', {
  options: {
    route: '/contact',
    url: 'views/contact.html'
  },
	data : data
});

setTimeout(function () {
     // works fine
     data.add({
		title : 'Three',
		nested : [
			33,
			2,
			333123
		]
	});
        // does not works
        data([some data with new elements]);
        data.reset([some data with new elements]);
}, 2000);
```

without server rendering i get on client

Uncaught TypeError: Cannot read property 'childNodes' of undefined on 7989
```javascript
// error line
 var childNodes = domElement.childNodes;
```

**Comment by oncesk** [comment]
i fixed it for me 

```javascript
			var self = this;
			this.data.removeAll();
			this.data.addMany(data);
```

**Comment by astoilkov** [comment]
This is a bug. This is probably related to recent changes in the way `blocks.observable.reset` works. I will check it out and fix it.

Thanks.

**Comment by astoilkov** [comment]
Hi,

I tried to replicate the issue but without success. You could download the test project from [here](https://dl.dropboxusercontent.com/u/4277603/jsblocks/jsblocks-reset-method.zip). You could install dependencies using `npm install` and run the project with `npm start` or server rendering with `npm run node`.

Can you take a look at the project and try to replicate the problem?

The JavaScript I used to try and replicate the problem.
```
var App = blocks.Application({
  history: 'pushState'
});

var data = blocks.observable([
    {
        title : 'One',
        nested : [
            1,
            2,
            3
        ]
    },
    {
        title : 'Two',
        nested : [
            111,
            222,
            333
        ]
    }
]);

App.View('Home', {
  options: {
    route: '/',
    url: 'views/home.html'
  }
});

App.View('Contact', {
  options: {
    route: '/contact',
    url: 'views/contact.html'
  },
    data : data
});

data.reset([{
  title : 'Three',
  nested : [
      33,
      2,
      333123
  ]
}]);
```

**Comment by oncesk** [comment]
Hi,

now i am too use data.reset and all fine, bug appears when i used data.removeAll()

**Comment by oncesk** [comment]
i paste your code but in the end i just add 

```javascript
setTimeout(function () {
	data.reset([{
		title : 'Four',
		nested : [
			444
		]
	}]);
}, 2000);
```

and error apears again

http://clip2net.com/s/3kRG8SQ
http://clip2net.com/s/3kRGeSe

**Comment by oncesk** [comment]
your code works as expected

**Comment by astoilkov** [comment]
Thanks a lot. Actually this was fixed couple of weeks ago but I didn't create a release until then. I will create a release today. Until then you could resolve your issue by getting the latest code from the repository `./dist` folder. I am closing this one.
