### ISSUE TITLE
Subviews how works?

### ISSUE THREAD

**Issue by norman784** [astoilkov/jsblocks#68]
I've trying to build an simple app, but the lack of third party examples / documentation makes it difficult, I saw that there are nested views, but how it works? I just have a simple view like:

```jade
div(data-query="view(Campaigns)")
  //- ... some random stuff, tables, etc
  div(data-qery="view(Form)")
```

and the js:

```javascript
App.View('Campaigns', {....});
App.View('Campaigns', 'Form', {....});
```

As can see there, form is a nested view, so I thought it need to be inside campaings view, but the view isn't loaded, how can I load this view, its b/c I don't want to have fat views so want to break into pieces, if not possible will try in server side with includes and all thats stuffs.

Also I can see that the view is loaded from the server with their html, but isn't showing even when I change their url.

PD: im using jade for templates, thats why the html is this way, but it renders ok on browser so isn't the problem there

Regards

**Comment by oncesk** [comment]
hi, you can use

```javascript
App.View('Campaigns', 'Form', {

			init : function () {
				console.log('initialized Form view');
                                this.isActive(true);
			},

			options : {
				url : 'you url for fetching view'
			}
		});
```

and you use isActive() function for change view visibility

**Comment by astoilkov** [comment]
Is the comment helped you. I am not sure where exactly is the problem. However, you could create a simple isolated project showing the issue and I could debug it. Another possible approach will be to create a simple project showing how Nested views work.

**Comment by norman784** [comment]
@astoilkov @oncesk sorry for the late response, I've made a [simple example](https://jsfiddle.net/norman784/u7m3oqL1/), seems that works when it doesn't have the route, but b/c I'm working with routes the form is hidden, also adding this.isActive(true) on init doesn't work either.

**Comment by astoilkov** [comment]
You could resolve your issue by manually activating the View. However, this seems to be a bug and I am going to investigate it further.

```
var App = blocks.Application();
App.View('Campaigns', {
    options: {
        route: 'campaigns'   
    },
    
    init: function () {
        App.Campaigns.Form.isActive(true);
    }
});

App.View('Campaigns', 'Form', {
    init: function() {
        
    }
});
```

**Comment by norman784** [comment]
I can activate, but if I fetch the view from a url the div stays empty

**Comment by astoilkov** [comment]
I see. I will investigate this in the next couple of days and will try to fix it and push an release.

**Comment by norman784** [comment]
ty
