### ISSUE TITLE
Nested views

### ISSUE THREAD

**Issue by g00glen00b** [astoilkov/jsblocks#7]
I'm quite confused about nested views. According to the documentation you should add the name of the parent view, for example:

    App.View('Parent', {});
    App.View('Parent', 'Child', {});

In the API docs on the other hand, there is no reference of this parent/child declaration.

---

I'm having quite a lot of problems with this setup, I'm always getting the same error in my log:

    Uncaught ReferenceError: Child is not defined

And I'm pretty sure that part of the script is executed. Also, when you switch the order, for example:

    App.View('Parent', 'Child', {});
    App.View('Parent', {});

I'm noticing that there's a high CPU usage and the page freezes.

---

Also, this doesn't really makes sense to me. I'm trying to make an individual component (for example a user profile component), but this can obviously be used in multiple parents. If I leave the parent viewname, then the component works individually, but it does not work in a nested situation.

**Comment by astoilkov** [comment]
Hi,

This is interesting. From the code snippet it seems that you are doing everything correctly. I tried the example from the documentation and it works correctly. It would be great to observe the code that replicates the issue so I could investigate it closely.

Until then I could suggest things to make your scenario work:

*  Do not define a child view and use a view that does not have parent:
```html
<script>
  App.View('Parent', {});
  App.View('Child', {});
</script>

<div data-query="view(Parent)">
  <section data-query="view($root.Child)">
  </section>
</div>
```

* Use a template

> Note: Templates usage could also be observed in the [shopping sample project](https://github.com/astoilkov/jsblocks-shopping-example)

```html
<script>
App.View('Parent', {
  Child: {
    
  }
});
</script>

<script id="profile" type="text/blocks-template">
  <!-- your template here -->
</script>

<div data-query="view(Parent)">
  <div data-query="template(profile, Child)">
  </div>
</div>
```

Additionally, I will update the API in order to include the parent view argument.

**Comment by g00glen00b** [comment]
Here's the code I'm using: https://github.com/g00glen00b/jsblocks-song-rate
It's using Browserify, but I don't think that would be the issue.

Anyways, I'm using `$root` now and now I indeed don't get an error, but it doesn't do anything either.

**Comment by g00glen00b** [comment]
I think I understand now why it couldn't find the childview. I was using it withing an `each()` inner block, so the context of `$this` was no longer the same as `Parent`.
