### ISSUE TITLE
Properties not resolved from inside a template included in each loop

### ISSUE THREAD

**Issue by apuravchauhan** [astoilkov/jsblocks#71]
This should have been very easy from the first look but I am not sure what am i doing wrong here.

Properties are not resolved if the template is included in each loop. 
Here is the plunker for the same.
http://plnkr.co/edit/jpGg4fAagzQuUhUtGPSM?p=preview

What is the right way of doing this.

Moreover what if inside the template I want to refer the properties via a custom variable lets say 'user' instead of $this.

**Comment by astoilkov** [comment]
Yes. This issue was resolved and commented [here](https://github.com/astoilkov/jsblocks/issues/55). However, it is still not part of a release. I will push a release this weak.

**Comment by astoilkov** [comment]
You could get the latest source from the `./dist` folder in order to resolve your issue.
