### ISSUE TITLE
Default collection set the model to default value

### ISSUE THREAD

**Issue by kuashe** [astoilkov/jsblocks#72]
Hi , 

It seems like creating collection with default values make the model that is related to it always set to first value of the default value in the collection .

http://plnkr.co/edit/4UgROWV8wHbqozP7IdRy?p=preview

		<html>
		  <head>
			<script src="http://jsblocks.com/jsblocks/blocks.js"></script>
			<script>
			var App = blocks.Application();
			
			var model = App.Model({
			  name : blocks.observable(), // Changing the observable to "App.Property()" help bypass this problem
			  init : function(){
				console.log(this.name())
			  }
			})
			
			var collection = App.Collection(model) //Removing the 'model' from collection can help bypass problem
			
			App.View('olap',{
			  collection : collection(  [ {name : "Joe"} , {name : "Kro"} ] ),
			  newModel : model(),
			})
			</script>
		  </head>
		  <body >
			<div data-query="view(olap)">
			  
			  <p>New model name : {{newModel.name}}</p><input data-query="val(newModel.name)"/> 
			  <div data-query="each(collection)">
				<h1>Hello, my name is {{name}} </h1>
			  </div>
			</div>
		  </body>
		</html>

**Comment by astoilkov** [comment]
Ok. I found the problem. I will push a fix tomorrow.
