### ISSUE TITLE
options query do not replace option value in some situations

### ISSUE THREAD

**Issue by oncesk** [astoilkov/jsblocks#74]
http://jsfiddle.net/3wagqq4h/2/

**Comment by astoilkov** [comment]
Ok. I will fix this. There are couple of issues with the new `reset` implementation that I should go through. During that time you could use `removeAll` and then `addMany` instead.

**Comment by Kanaye** [comment]
After thinking a bit about this issue I have a question:
Should we update the value of the select when the options get reseted / replaced?
Cause it can be missleading for the user if the browser shows that the selected value updated but the value in the application did not.
On the otherside it might be unexpected for the developer if the value get's updated with the reset.
To make more clear what I mean:
```html
<select data-query="options(myOptions, {text:'text', value:'id'}).val(myVal)"></select>
```
```javascript
var myOptions = blocks.observable([{
  id: '1', 
  text: 'Option 1'
}]);
var myVal = blocks.observable('1');

blocks.query({
   myOptions: myOptions,
   myVal: myVal
});


myOptions.reset([{
  id: '42',
  text: 'The answer to everything'
}]);

// Should 'myVal' now have the value 1 or 42 as the browser displays ? 
// Currently the value would be 1 (even if the dom would get updated correctly).
```
What do you think ?

**Comment by astoilkov** [comment]
I think the selected item shouldn't be one that does not exist. In this case after reseting the `1` doesn't exist so in my opinion we should just select the first item because this for me is the most correct value in scenario when the desired selected value is not present.

Did you understand what I want to say?

**Comment by Kanaye** [comment]
Yes. I think I've got it.
I agree that the behavior is logical the best beside not removing the selected value, but that's on the dev building the app.
