### ISSUE TITLE
Please update NPM

### ISSUE THREAD

**Issue by antony** [astoilkov/jsblocks#79]
Hi There,

NPM still has version 0.1.0 - please can you update it to 0.3.3?

Cheers,
Antony

**Comment by astoilkov** [comment]
You are probably mistaken with the `jsblocks` module. You will need to use the [`blocks` module](https://www.npmjs.com/package/blocks).

**Comment by antony** [comment]
Ah! That was fast :)

You should probably then delete and purge the jsblocks npm module, as it is misleading

**Comment by astoilkov** [comment]
I agree. I will do it today.
