### ISSUE TITLE
Route params

### ISSUE THREAD

**Issue by oknoorap** [astoilkov/jsblocks#81]
When I read this tutorial http://jsblocks.com/learn/view-routing-and-history, and tried on jsfiddle
```{{route.type}}``` doesn't rendered why?

link:
```<a href="#" data-query="navigateTo(Product, {type: 'test'})">Products</a>```

```
<div data-query="view(Product)">
Product {{route.type}}
</div>
```

how to do the right way?

**Comment by astoilkov** [comment]
Hi @oknoorap 

The `{{route}}` property is not available out of the box. You will need to create such property. You can do that in the `View.routed` method.

```javascript
App.View('ViewName', {
  route: {
    type: blocks.observable('')
  },

  routed: function (params) {
    this.route.type(params.type);
  }
});
```

**Comment by oknoorap** [comment]
okay thanks.
