### ISSUE TITLE
Selectbox not sync.

### ISSUE THREAD

**Issue by oknoorap** [astoilkov/jsblocks#84]
Code:
http://jsfiddle.net/hvpforp0/

When adding new collection, selectbox not sync. what's wrong?

**Comment by oknoorap** [comment]
@astoilkov

**Comment by astoilkov** [comment]
Sorry for the late response. This seems to be a bug. I have labeled it and will take a look at it in order to find a solution.

Thanks for reporting it.

**Comment by Kanaye** [comment]
For the record: I fixed this one, but it's kind of dirty... I will look for cleaner fix befor creatign a pull request.
