### ISSUE TITLE
when are parentheses needed when calling observables in double-brace expressions?

### ISSUE THREAD

**Issue by lilchow** [astoilkov/jsblocks#85]
In the online documentation on observable (http://jsblocks.com/learn/working-with-observables-introduction) I saw the observable followed by parentheses when called in double-brace expression in one place, such as "My name is {{firstName()}}! " but not followed by anything in a different place, such as "My name is {{fullName}} and I am {{age}} years old. " what is the rule here? Or are they actually totally interchangeable? Thanks!

**Comment by astoilkov** [comment]
Hi,

The simple answer: Always use parentheses
The more complicated answer: Parentheses are needed only when the value is an expression. Let me give you an example.

  - `firstName` (not needed)
  - `'hello' + firstName()` (needed)
  - `!firstName()` (needed)
  - `age` (not needed)
  - `age() * age()` (needed)
  - `!age()` (needed)

The way you can think about it is if you have anything other than the variable itself you should add parentheses. However, you could add a rule to always add parentheses and never worry.

P.S. I should probably add this to the documentation so it is more clear.
