### ISSUE TITLE
doesn't update the elements in input

### ISSUE THREAD

**Issue by ivancduran** [astoilkov/jsblocks#88]
I have this code, the elements redraw perfectly except the input, the input always stay on the same value.

Best Regards.

```javascript
blocks.query({
	price: blocks.observable(1),
	ratio: blocks.observable(0.2),
	onClick:function(){
		this.price(this.price() +1 );
		this.ratio(this.ratio() +0.5 );
		console.log(this);
	}
});
```
```html
<input value="{{price * ratio}}">
<span>{{price * ratio}}</span>
<div>{{price * ratio}}</div>

<button data-query="click(onClick)">click</button>
```

**Comment by Kanaye** [comment]
Use the data-query "val()" for inputs.
Like so: [jsfiddle](http://jsfiddle.net/1b2ebcx4/).

Have a nice day.

**Comment by ivancduran** [comment]
Thanks for the info, works fine now.

The "{{expressions}} syntax" shows that, probably need a note: http://jsblocks.com/learn/syntax-expressions-syntax

**Comment by astoilkov** [comment]
Actually, I think this scenario should work using an expression. I will label this as enhancement.
