### ISSUE TITLE
With query

### ISSUE THREAD

**Issue by g00glen00b** [astoilkov/jsblocks#9]
The API documentation of the `with()` query is confusing. The examples are using `view(ViewName, '$context')` in stead of `with()`. Is it meant to be used with the `view()` query, or are the examples wrong?

**Comment by astoilkov** [comment]
You are absolutely correct. It is an error. It should be `with` instead of `view`. I will fix this and also go through the entire API documentation to look for other errors.

Thanks for the reported issue.
