### ISSUE TITLE
Server side rendering tutorial

### ISSUE THREAD

**Issue by kokujin** [astoilkov/jsblocks#92]
Can someone explain or point me to a a simple tutorial on how to add server side rendering using JSblocks to an existing Express app? Thanks

**Comment by astoilkov** [comment]
Hi @kokujin,

As described [here](http://jsblocks.com/learn/introduction-server-side-rendering) you could use the boilerplate code from there and switch the express instance that you are using.

```
var blocks = require('blocks');
var server = blocks.server({
    // the port at which your application will be run
    port: 8000,

    // the folder where your application files like .html, .js and .css are going to be
    // the value is passed to express.static() middleware
    static: 'app',

    // caches pages result instead of executing them each time
    // disabling cache could impact performance
    cache: true,

    // provide an express middleware function or an array of middleware functions
    // use: [compression(), bodyParser()]
    use: null
});

// returns the `express` app `blocks.server` is using internally
var app = server.express();

// use app instead of your own express instance
```

**Comment by kokujin** [comment]
Thanks @astoilkov for the speedy reply. I am skeptical though. I would like to use the latest Express version, and JSblocks is not tracking that.

So actually, fro the link you sent me, I can initialize, all my custom and vendor middleware just as in a normal Express app?

**Comment by astoilkov** [comment]
Yeah. Currently there is no way to use the server side rendering as express middleware. However, the code is designed to do just that. It will be easy to add this feature. I created a new issue for this: https://github.com/astoilkov/jsblocks/issues/95

**Comment by astoilkov** [comment]
I am closing this. If you have more questions feel free to open a new issue.
