### ISSUE TITLE
Observable with the same name not set to the good Model

### ISSUE THREAD

**Issue by kuashe** [astoilkov/jsblocks#96]
http://plnkr.co/edit/7MZz1ww6kN43WqcRUWMd?p=preview

Is this suppose to be the normal behaviour ?

Edit : Sorry Wrong Plunk

**Comment by Kanaye** [comment]
I looked a (little) bit into this and I think that's not what's supposed to happen.
blocks is somehow mapping an instance of the other (right) Model to the Collection, even if we give the wrong one as an argument to ``collection.add``.
I will look into this in the next days.

**Comment by Kanaye** [comment]
Okay as I see now, this bug is already fixed in the newest (not released) version of jsblocks.
I'm not sure why but my Chromium was using an older version of jsblocks instead of the current build in my filesystem :disappointed:. Also a way spending my time ....

**Comment by astoilkov** [comment]
Bad and good news at the same time. :) Be sure to check the box "Disable Cache when DevTools is open" in Chrome DevTools.

**Comment by Kanaye** [comment]
I have checked this box... Not the first time i'm struggling with caches :smile:. I had to kill the browser profile of my chromium to get it using the right file. It's good a thing I'm using chromium only to debug, otherwise i'd be sad.

**Comment by astoilkov** [comment]
So. Should I close this?

**Comment by Kanaye** [comment]
Yes. As it's fixed in the next release i don't see a reason to let ths left open.

**Comment by astoilkov** [comment]
Hey @kuashe. Closing this. I plan to release a new version next week so you could expect the bug included there.
